{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "e-session.serviceAccountName" . }}
  labels:
{{ include "e-session.labels" . | indent 4 }}
{{- end -}}
